import { build } from "esbuild";

await build({
  entryPoints: ["actions/pr-meme/src/main.ts"],
  outfile: "actions/pr-meme/dist/index.js",
  bundle: true,
  platform: "node",
  target: "node24",
  format: "esm",
  banner: {
    js: '// Generated by pnpm build; do not edit.\nimport { createRequire } from "node:module"; const require = createRequire(import.meta.url);',
  },
});
